### PR TITLE
added support for docker-compose file inclusion

### PR DESCRIPTION
**Pull request by pelger**

### CODE REVIEW

**Comment by davidmarkclements** [comment]
One question, I've looked through and haven't spotted it

When we include a docker-compose file, is there a way to single out individual services to ensure they run in a container

**Comment by davidmarkclements** [comment]
Otherwise LGTM

**Comment by davidmarkclements** [comment]
(provisionally approved, regardless of direction based on comment)

**Comment by pelger** [comment]
Yep when we include the compose file, elements that have the `build` directive are treated as processes, elements with the `image` directive are run as containers using the docker API - make sense?

**Comment by davidmarkclements** [comment]
yes LGTM

**Pull request merged**
